Repository IGNF/cartes.gouv.fr-entree-carto, pull requests merged in 2024-08, with the labels that each got.

#291 fix(position:css): gestion en position absolue du bouton "menu widget"
  src/components/menu/MenuLateralWrapper.vue
Labels: enhancement

#292 fix(localStorage): liste de controls ajoutés à la première visite
  src/composables/controls.js
  src/stores/mapStore.js
Labels: bug

#293 fix(header): ajout de la navigation dans le menu hamburger mobile
  src/views/Main.vue
Labels: bug

#294 Feature : ajout des widgets itinéraire et isochrone
  geopf-extensions-openlayers-1.0.0-beta.0-140.tgz
  geopf-extensions-openlayers-1.0.0-beta.0-143.tgz
  package.json
  src/components.d.ts
  src/components/carte/Controls.vue
  src/components/carte/control/Route.vue
  src/composables/controls.js
Labels: feature

#302 🚑 mes outils apres ajouter des outils
  src/components/menu/MenuControl.vue
Labels: enhancement

#303 fix(css:Search): reduction de la largeur et meilleur centrage
  geopf-extensions-openlayers-1.0.0-beta.0-143.tgz
  geopf-extensions-openlayers-1.0.0-beta.0-148.tgz
  package.json
  src/components/carte/control/SearchEngine.vue
Labels: enhancement

#301 Collecte Eulerian des interaction avec les widgets
  src/components/carte/Controls.vue
  src/components/carte/control/Isocurve.vue
  src/composables/controls.js
  src/main.ts
  src/plugins/Eulerian.js
Labels: question
