Repository IGNF/cartes.gouv.fr-entree-carto, pull requests merged in 2024-09, with the labels that each got.

#307 Ajout du CHANGELOG
  CHANGELOG.md
  README.md
  docs/eulerian/Eulerian_Formation interne SIG_Cas pratique.pdf
  docs/eulerian/Eulerian_Formation interne SIG_Taux de Rebond et durée de visite.pdf
  docs/eulerian/Eulerian_Formation interne SIG_données de contenus.pdf
  docs/eulerian/Eulerian_Formation interne SIG_données de visite.pdf
  docs/eulerian/Eulerian_Formation interne SIG_données sur les actions.pdf
  docs/eulerian/Eulerian_Formation interne SIG_indicateurs clés.pdf
Labels: documentation

#245 🌟 catalogue avec barre de recherche
  public/data/edito.json
  src/components.d.ts
  src/components/CartoAndTools.vue
  src/components/carte/Layer/Layers.vue
  src/components/carte/Map.vue
  src/components/carte/View.vue
  src/components/menu/LeftMenuTool.vue
  src/components/menu/MenuCatalogue.vue
  src/components/menu/MenuControl.vue
  src/components/menu/MenuLateralWrapper.vue
  src/components/menu/catalogue/DataLayerCatalogue.vue
  src/components/menu/catalogue/LayerCatalogue.vue
  src/components/menu/catalogue/LayerList.vue
  src/components/menu/catalogue/MenuCatalogue.vue
  src/components/menu/catalogue/MenuCatalogueThematique.vue
  src/composables/searchInArray.js
  src/stores/dataStore.js
Labels: feature

#312 Ajout des options de preload sur les tuiles
  src/components/carte/Layer/Layer.vue
Labels: enhancement

#310 Partager une carte
  .vscode/settings.json
  public/data/edito.json
  src/components.d.ts
  src/components/carte/Controls.vue
  src/components/carte/Map.vue
  src/components/carte/control/LayerSwitcher.vue
  src/components/carte/control/Share.vue
  src/composables/controls.js
  src/composables/urlParams.js
  src/router/index.ts
  src/stores/dataStore.js
  src/stores/mapStore.js
  src/views/Embed.vue
  src/views/Main.vue
Labels: feature

#309 Activation des tracker Eulerain sur les actions boutons des widgets
  src/components/carte/Controls.vue
  src/components/carte/control/Attributions.vue
  src/components/carte/control/FullScreen.vue
  src/components/carte/control/Isocurve.vue
  src/components/carte/control/LayerSwitcher.vue
  src/components/carte/control/Legends.vue
  src/components/carte/control/MeasureArea.vue
  src/components/carte/control/MeasureAzimuth.vue
  src/components/carte/control/MeasureLength.vue
  src/components/carte/control/OverviewMap.vue
  src/components/carte/control/ReverseGeocode.vue
  src/components/carte/control/Route.vue
  src/components/carte/control/ScaleLine.vue
  src/components/carte/control/SearchEngine.vue
  src/components/carte/control/Zoom.vue
  src/components/menu/MenuLateralNavButton.vue
  src/components/modals/ModalConsent.vue
  src/components/modals/ModalInformation.vue
  src/components/modals/ModalTheme.vue
  src/composables/actionEulerian.js
  src/composables/controls.js
  src/main.ts
  src/plugins/Eulerian.js
  src/stores/dataStore.js
  src/stores/mapStore.js
Labels: feature

#314 Ajout du composant Territories
  public/data/edito.json
  src/components.d.ts
  src/components/carte/Controls.vue
  src/components/carte/control/Share.vue
  src/components/carte/control/Territories.vue
  src/composables/controls.js
  src/stores/dataStore.js
Labels: feature
