Repository IGNF/cartes.gouv.fr-entree-carto, pull requests merged in 2024-12, with the labels that each got.

#379 Page d'impression
  package.json
  src/components.d.ts
  src/components/CartoAndTools.vue
  src/components/carte/Carto.vue
  src/components/carte/Controls.vue
  src/components/carte/Layer/Layer.vue
  src/components/carte/Layer/Layers.vue
  src/components/carte/Map.vue
  src/components/carte/View.vue
  src/components/carte/control/Attributions.vue
  src/components/carte/control/ControlList.vue
  src/components/carte/control/Drawing.vue
  src/components/carte/control/ElevationPath.vue
  src/components/carte/control/FullScreen.vue
  src/components/carte/control/GetFeatureInfo.vue
  src/components/carte/control/Isocurve.vue
  src/components/carte/control/LayerImport.vue
  src/components/carte/control/LayerSwitcher.vue
  src/components/carte/control/Legends.vue
  src/components/carte/control/MeasureArea.vue
  src/components/carte/control/MeasureAzimuth.vue
  src/components/carte/control/MeasureLength.vue
  src/components/carte/control/MousePosition.vue
  src/components/carte/control/OverviewMap.vue
  src/components/carte/control/Print.vue
  src/components/carte/control/ReverseGeocode.vue
  src/components/carte/control/Route.vue
  src/components/carte/control/ScaleLine.vue
  src/components/carte/control/SearchEngine.vue
  src/components/carte/control/Territories.vue
  src/components/carte/control/Zoom.vue
  src/composables/controls.js
  src/composables/keys.js
  src/icons.ts
Labels: feature

#404 Upgrade dsfr 1.11.2 --> 1.13.0
  package.json
  src/main.ts
Labels: enhancement

#406 fix: Affichage Panel plein écran avec scrolle sur footer
  src/components/carte/Controls.vue
Labels: bug

#409 Fix sur la syncro de l'ordre des couches avec le permalien
  src/components/carte/control/LayerSwitcher.vue
  src/stores/mapStore.js
Labels: bug

#410 fix(permalink): correction du #400, les widgets par defaut sont toujours ajoutés à la carte
  src/composables/controls.js
  src/composables/urlParams.js
  src/stores/mapStore.js
Labels: bug

#425 fix: change la langue du html de base
  index.html
Labels: bug

#431 Recette/print 64
  src/components/carte/Carto.vue
  src/components/carte/Controls.vue
  src/components/carte/Map.vue
  src/components/carte/control/Attributions.vue
  src/components/carte/control/ControlList.vue
  src/components/carte/control/Drawing.vue
  src/components/carte/control/ElevationPath.vue
  src/components/carte/control/FullScreen.vue
  src/components/carte/control/GetFeatureInfo.vue
  src/components/carte/control/Isocurve.vue
  src/components/carte/control/LayerImport.vue
  src/components/carte/control/LayerSwitcher.vue
  src/components/carte/control/Legends.vue
  src/components/carte/control/MeasureArea.vue
  src/components/carte/control/MeasureAzimuth.vue
  src/components/carte/control/MeasureLength.vue
  src/components/carte/control/MousePosition.vue
  src/components/carte/control/OverviewMap.vue
  src/components/carte/control/Print.vue
  src/components/carte/control/ReverseGeocode.vue
  src/components/carte/control/Route.vue
  src/components/carte/control/ScaleLine.vue
  src/components/carte/control/SearchEngine.vue
  src/components/carte/control/Share.vue
  src/components/carte/control/Territories.vue
  src/components/carte/control/Zoom.vue
Labels: bug

#438 🚑 menu control size fix
  src/components/menu/MenuControl.vue
Labels: bug

#445 fix(search): resultats d'autocomplete améliorés
  DRAFT_CHANGELOG.md
  geopf-extensions-openlayers-1.0.0-beta.1-296.tgz
  geopf-extensions-openlayers-1.0.0-beta.1-313.tgz
  package.json
  src/components/carte/Controls.vue
Labels: enhancement
