Repository IGNF/cartes.gouv.fr-entree-carto, pull requests merged in 2024-07, with the labels that each got.

#256 feat(measures): Ajout des outils de mesures
  geoportal-extensions-openlayers-1.0.0-beta.82.tgz
  geoportal-extensions-openlayers-1.0.0-beta.95.tgz
  package.json
  src/components.d.ts
  src/components/carte/Controls.vue
  src/components/carte/control/MeasureArea.vue
  src/components/carte/control/MeasureAzimuth.vue
  src/components/carte/control/MeasureLength.vue
  src/components/menu/MenuControl.vue
  src/composables/controls.js
Labels: feature, Maquette wanted

#255 feat(localstorage): ajout des clefs dans le LocalStorage
  src/components/CartoAndTools.vue
  src/components/menu/MenuControl.vue
  src/stores/dataStore.js
  src/stores/mapStore.js
Labels: feature

#267 feat(header): ajout mention beta derrière le titre
  src/views/Main.vue
Labels: feature

#270 Fix(css): Better buttons positions into the grid
  geoportal-extensions-openlayers-1.0.0-beta.107.tgz
  geoportal-extensions-openlayers-1.0.0-beta.97.tgz
  package.json
  src/components/carte/Controls.vue
  src/components/carte/control/LayerSwitcher.vue
  src/components/carte/control/ScaleLine.vue
  src/components/menu/MenuLateralWrapper.vue
Labels: bug, enhancement

#271 Gestion des cookies et Eulerian
  src/components.d.ts
  src/components/menu/MenuLateralWrapper.vue
  src/components/modals/ModalConsent.vue
  src/components/modals/ModalTheme.vue
  src/composables/footerParams.js
  src/main.ts
  src/plugins/Eulerian.js
  src/router/index.ts
  src/views/Main.vue
  vite.config.ts
Labels: feature

#272 Ajout du composant des Légendes
  geoportal-extensions-openlayers-1.0.0-beta.103.tgz
  geoportal-extensions-openlayers-1.0.0-beta.107.tgz
  package.json
  src/components.d.ts
  src/components/carte/Controls.vue
  src/components/carte/control/Legends.vue
  src/components/menu/MenuControl.vue
  src/composables/controls.js
Labels: feature, Maquette wanted

#282 Affichage d'une modale d'information activable via l'edito
  .gitignore
  public/data/edito.json
  src/components.d.ts
  src/components/modals/ModalInformation.vue
  src/stores/dataStore.js
  src/stores/mapStore.js
  src/views/Load.vue
Labels: feature

#283 style(menu-button): Le bouton d'ouverture du menu est passé en composant DSFRButton
  src/components.d.ts
  src/components/menu/MenuLateralNavButton.vue
  src/components/menu/MenuLateralWrapper.vue
Labels: bug

#285 🚑 switch theme color menu
  src/components/menu/MenuLateralWrapper.vue
Labels: bug

#273 🚧 maj du menu selon maquette
  src/components.d.ts
  src/components/CartoAndTools.vue
  src/components/carte/Controls.vue
  src/components/menu/MenuControl.vue
  src/components/menu/MenuLateralWrapper.vue
  src/composables/controls.js
Labels: enhancement
