Repository IGNF/cartes.gouv.fr-entree-carto, pull requests merged in 2024-10, with the labels that each got.

#328 🚑 fix https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/317
  src/stores/mapStore.js
Labels: bug

#333 fix(mouseposition): corrige retours recette #323 sur le mousePosition
  geopf-extensions-openlayers-1.0.0-beta.0-180.tgz
  geopf-extensions-openlayers-1.0.0-beta.0-182.tgz
  package.json
Labels: bug

#330 Fix Recette : Réorganisation des boutons et des panels (menu, carto)
  src/components/CartoAndTools.vue
  src/components/carte/Controls.vue
  src/components/carte/control/Share.vue
  src/components/menu/MenuLateralWrapper.vue
Labels: bug, enhancement

#337 Changement de projection du centre en geographique
  src/assets/fullscreen.svg
  src/assets/map.svg
  src/components/carte/Carto.vue
  src/components/carte/Controls.vue
  src/components/carte/View.vue
  src/stores/mapStore.js
Labels: enhancement

#326 📖 ajout de la doc sur les componants
  src/components/carte/Carto.vue
  src/components/carte/Controls.vue
  src/components/carte/Map.vue
  src/components/carte/View.vue
  src/components/menu/MenuControl.vue
  src/components/menu/MenuLateralNavButton.vue
  src/components/menu/MenuLateralWrapper.vue
Labels: enhancement

#329 🚑 fix: corrections sur le composant de partage
  index.html
  public/data/edito.json
  src/components.d.ts
  src/components/carte/control/Share.vue
  src/icons.ts
  src/stores/mapStore.js
Labels: bug

#341 fix(share:mail): pas de destinataire par défaut + saut de ligne dans body du mail
  public/data/edito.json
  src/components/carte/control/Share.vue
Labels: bug, enhancement

#348 widget par défaut : searchengine et layswitcher
  src/components/carte/Controls.vue
  src/composables/controls.js
Labels: enhancement

#345 Ajout d'un marker de positionnement (searchEngine)
  geopf-extensions-openlayers-1.0.0-beta.0-193.tgz
  geopf-extensions-openlayers-1.0.0-beta.0-197.tgz
  package.json
  src/assets/geolocation.svg
  src/components/carte/Controls.vue
  src/components/carte/control/SearchEngine.vue
Labels: enhancement

#353 Versionning du localStorage
  src/stores/mapStore.js
Labels: bug

#354 Feature/gfi
  DRAFT_CHANGELOG.md
  geopf-extensions-openlayers-1.0.0-beta.0-197.tgz
  geopf-extensions-openlayers-1.0.0-beta.0-207.tgz
  geopf-extensions-openlayers-1.0.0-beta.0-211.tgz
  package.json
  src/components.d.ts
  src/components/carte/Controls.vue
  src/components/carte/control/GetFeatureInfo.vue
  src/composables/controls.js
  src/composables/searchInArray.js
Labels: feature

#325 Feature/profil alti
  src/components.d.ts
  src/components/carte/Controls.vue
  src/components/carte/control/ElevationPath.vue
  src/components/carte/control/Share.vue
  src/components/menu/LeftMenuTool.vue
  src/components/menu/MenuLateralNavButton.vue
  src/components/menu/MenuLateralWrapper.vue
  src/components/menu/RightMenuTool.vue
  src/composables/controls.js
Labels: feature
