Repository IGNF/cartes.gouv.fr-entree-carto, pull requests merged in 2025-04, with the labels that each got.

#529 Passage à un fichier de conf unique
  DRAFT_CHANGELOG.md
  env/.env.demo
  env/.env.development
  env/.env.development-local
  env/.env.docker-dev-local
  env/.env.docker-local
  env/.env.production
  env/.env.production.bak
  public/data/entreeCarto.json
  src/stores/dataStore.js
Labels: enhancement

#532 Eviter le chargement de toutes les projections
  src/components/carte/Map.vue
Labels: enhancement

#567 🚑 fenêtre de croquis cachée par le panel entrée carto
  DRAFT_CHANGELOG.md
  src/components/CartoAndTools.vue
  src/components/menu/MenuLateralWrapper.vue
Labels: recette

#575 💄 on enlève le footer en mode mobile
  src/components/CartoAndTools.vue
  src/views/Main.vue
Labels: recette

#576 Gestion des positions dans le permalien
  DRAFT_CHANGELOG.md
  geopf-extensions-openlayers-1.0.0-beta.4.tgz
  src/components/CartoAndTools.vue
  src/components/carte/Layer/Layer.vue
  src/components/carte/Layer/Layers.vue
  src/components/carte/control/LayerImport.vue
  src/components/carte/control/LayerSwitcher.vue
  src/components/menu/bookmarks/MenuBookMarkEntry.vue
  src/components/modals/ModalTheme.vue
  src/features/layer.js
  src/features/share.js
  src/icons/NotificationClose.vue
  src/stores/mapStore.js
  src/views/Main.vue
Labels: enhancement

#579 🌟 enregistrement dans menu contextuel
  DRAFT_CHANGELOG.md
  src/components/carte/Controls.vue
  src/components/menu/MenuTierce.vue
  src/stores/domStore.js
Labels: feature
