Repository IGNF/cartes.gouv.fr-entree-carto, pull requests merged in 2025-02, with the labels that each got.

#478 💄 upgrade de vue dsfr à la dernière version 8.1.1
  DRAFT_CHANGELOG.md
  package.json
  src/components/carte/control/ShareModal.vue
  src/components/menu/MenuLateralWrapper.vue
  src/components/menu/MenuTierce.vue
  src/components/menu/RightMenuTool.vue
  src/components/menu/catalogue/DataLayerCatalogue.vue
  src/components/menu/catalogue/MenuCatalogue.vue
  src/components/menu/catalogue/MenuCatalogueThematique.vue
  src/icons.ts
  src/main.ts
  vite.config.ts
Labels: dependencies

#484 🚑 css height
  src/components/menu/catalogue/MenuCatalogue.vue
Labels: bug

#488 fix(advanced-search): qui dépasse notamment en mode cadastre
  DRAFT_CHANGELOG.md
  src/components/carte/control/SearchEngine.vue
Labels: bug

#489 Fix implémentation catalogue
  DRAFT_CHANGELOG.md
  src/components/carte/Controls.vue
  src/components/menu/catalogue/DataLayerCatalogue.vue
  src/components/menu/catalogue/LayerCatalogue.vue
  src/components/menu/catalogue/LayerList.vue
  src/components/menu/catalogue/MenuCatalogue.vue
  src/stores/dataStore.js
Labels: bug

#498 datastore: update filter by layer
  DRAFT_CHANGELOG.md
  geopf-extensions-openlayers-1.0.0-beta.2-358.tgz
  package.json
  src/components/carte/Controls.vue
  src/components/menu/catalogue/DataLayerCatalogue.vue
  src/stores/dataStore.js
Labels: enhancement

#500 💄 🌟 modif du bouton copier selon maquette UX
  DRAFT_CHANGELOG.md
  env/.env.stage
  src/components.d.ts
  src/components/carte/control/ShareModal.vue
  src/components/utils/TextCopyToClipboard.vue
Labels: enhancement
