Repository IGNF/cartes.gouv.fr-entree-carto, pull requests merged in 2025-01, with the labels that each got.

#448 feat(drawing): styling div always top left
  geopf-extensions-openlayers-1.0.0-beta.1-331.tgz
  geopf-extensions-openlayers-1.0.0-beta.2-323.tgz
  package.json
  src/components/carte/control/Drawing.vue
Labels: feature

#452 feat(layer:tms): ajout de l'option declutter à true en option des TMS
  src/components/carte/Layer/Layer.vue
  src/composables/layer.js
Labels: enhancement

#456 fix: menu btns visible over advanced search
  src/components/menu/MenuLateralWrapper.vue
Labels: bug

#455 Feature/right click
  DRAFT_CHANGELOG.md
  geopf-extensions-openlayers-1.0.0-beta.1-306.tgz
  geopf-extensions-openlayers-1.0.0-beta.2-333.tgz
  package.json
  src/components.d.ts
  src/components/CartoAndTools.vue
  src/components/carte/Controls.vue
  src/components/carte/control/ContextMenu.vue
  src/composables/controls.js
  src/stores/appStore.js
Labels: feature

#468 🌟 catalogue ajouté au menu contextuel
  DRAFT_CHANGELOG.md
  src/components/carte/Controls.vue
  src/components/menu/MenuLateralNavButton.vue
  src/stores/mapStore.js
Labels: feature

#472 🚑 mode mobile context menu
  DRAFT_CHANGELOG.md
  package.json
  src/components/carte/control/ContextMenu.vue
Labels: bug

#473 fix(menu): icones au dessus menu tierce (il manquait une virgule)
  src/components/menu/MenuLateralWrapper.vue
Labels: bug
