Repository IGNF/cartes.gouv.fr-entree-carto, pull requests merged in 2025-07, with the labels that each got.

#640 Synchronisation de l'authentification avec cartes.gouv.fr
  .docker-dev/carto/Dockerfile
  env/.env.docker-local
  package.json
  src/services/ServiceBase.js
  src/services/ServiceUsers.js
  src/views/Main.vue
Labels: bug

#642 Fix sur les emprises sur le zoomToExtent pour les TMS
  DRAFT_CHANGELOG.md
  env/.env.docker-local
  src/components/carte/control/LayerSwitcher.vue
  src/stores/dataStore.js
Labels: bug

#649 Ajout fonctionnalité : Copie du permalien dans le menu des favoris
  DRAFT_CHANGELOG.md
  src/components/menu/bookmarks/MenuBookMarkDataList.vue
  src/components/menu/bookmarks/MenuBookMarkEntry.vue
  src/composables/urlParams.js
  src/features/permalink.js
  src/features/translation.js
Labels: feature

#671 Feat/mouseposition edit coords
  DRAFT_CHANGELOG.md
  geopf-extensions-openlayers-1.0.0-beta.5-401.tgz
  src/components/carte/Controls.vue
  src/components/carte/control/MousePosition.vue
Labels: enhancement
