Repository IGNF/cartes.gouv.fr-entree-carto, pull requests merged in 2025-03, with the labels that each got.

#503 Evol(Catalog) : Mise en cohérence edito.json avec layers.json et amélioration du catalogue
  DRAFT_CHANGELOG.md
  public/data/edito.json
  src/components/menu/catalogue/DataLayerCatalogue.vue
  src/components/menu/catalogue/LayerList.vue
  src/stores/dataStore.js
Labels: enhancement

#507 Fix/catalogue autres produecteur
  DRAFT_CHANGELOG.md
  src/components.d.ts
  src/components/menu/catalogue/LayerCatalogue.vue
  src/components/utils/CustomAccordeon.vue
  src/components/utils/TextCopyToClipboard.vue
  src/stores/dataStore.js
Labels: feature, enhancement

#508 Search(feat): recherche avancée par coordonnées dans la recherche avancée
  DRAFT_CHANGELOG.md
  geopf-extensions-openlayers-1.0.0-beta.2-358.tgz
  geopf-extensions-openlayers-1.0.0-beta.3-363.tgz
  package.json
  src/components/carte/Controls.vue
Labels: feature, enhancement

#509 feat(compute/drawing): activation des boutons d'export
  DRAFT_CHANGELOG.md
  src/components/carte/control/Drawing.vue
  src/components/carte/control/ElevationPath.vue
  src/components/carte/control/Isocurve.vue
  src/components/carte/control/Route.vue
Labels: feature

#516 opti perf de chargement catalogue
  DRAFT_CHANGELOG.md
  src/components/menu/catalogue/DataLayerCatalogue.vue
  src/components/menu/catalogue/MenuCatalogue.vue
  src/stores/dataStore.js
Labels: bug, enhancement
